/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alper
 */
public class HesapMakinesi extends javax.swing.JFrame {
   double result = 0;
   double input1;
   double input2;
   int ps;
   
    public HesapMakinesi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton25 = new javax.swing.JButton();
        txt_ekran = new javax.swing.JTextField();
        btn_sifir = new javax.swing.JButton();
        btn_virgul = new javax.swing.JButton();
        btn_topla = new javax.swing.JButton();
        btn_uc = new javax.swing.JButton();
        btn_esittir = new javax.swing.JButton();
        btn_cikart = new javax.swing.JButton();
        btn_carp = new javax.swing.JButton();
        btn_bol = new javax.swing.JButton();
        btn_iki = new javax.swing.JButton();
        btn_bir = new javax.swing.JButton();
        btn_alti = new javax.swing.JButton();
        btn_bes = new javax.swing.JButton();
        btn_dort = new javax.swing.JButton();
        btn_dokuz = new javax.swing.JButton();
        btn_kok = new javax.swing.JButton();
        btn_arti_eksi = new javax.swing.JButton();
        btn_sil = new javax.swing.JButton();
        btn_yedi = new javax.swing.JButton();
        btn_sekiz = new javax.swing.JButton();

        jButton25.setBackground(new java.awt.Color(123, 123, 123));
        jButton25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("=");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_ekran.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txt_ekran.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ekran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ekranActionPerformed(evt);
            }
        });

        btn_sifir.setBackground(new java.awt.Color(123, 123, 123));
        btn_sifir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sifir.setForeground(new java.awt.Color(255, 255, 255));
        btn_sifir.setText("0");
        btn_sifir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sifirActionPerformed(evt);
            }
        });

        btn_virgul.setBackground(new java.awt.Color(97, 97, 97));
        btn_virgul.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_virgul.setForeground(new java.awt.Color(255, 255, 255));
        btn_virgul.setText(",");
        btn_virgul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_virgulActionPerformed(evt);
            }
        });

        btn_topla.setBackground(new java.awt.Color(255, 153, 51));
        btn_topla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_topla.setForeground(new java.awt.Color(255, 255, 255));
        btn_topla.setText("+");
        btn_topla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_toplaActionPerformed(evt);
            }
        });

        btn_uc.setBackground(new java.awt.Color(123, 123, 123));
        btn_uc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_uc.setForeground(new java.awt.Color(255, 255, 255));
        btn_uc.setText("3");
        btn_uc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ucActionPerformed(evt);
            }
        });

        btn_esittir.setBackground(new java.awt.Color(255, 153, 51));
        btn_esittir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_esittir.setForeground(new java.awt.Color(255, 255, 255));
        btn_esittir.setText("=");
        btn_esittir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_esittirActionPerformed(evt);
            }
        });

        btn_cikart.setBackground(new java.awt.Color(255, 153, 51));
        btn_cikart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_cikart.setForeground(new java.awt.Color(255, 255, 255));
        btn_cikart.setText("-");
        btn_cikart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikartActionPerformed(evt);
            }
        });

        btn_carp.setBackground(new java.awt.Color(255, 153, 51));
        btn_carp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_carp.setForeground(new java.awt.Color(255, 255, 255));
        btn_carp.setText("x");
        btn_carp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carpActionPerformed(evt);
            }
        });

        btn_bol.setBackground(new java.awt.Color(255, 153, 51));
        btn_bol.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_bol.setForeground(new java.awt.Color(255, 255, 255));
        btn_bol.setText("/");
        btn_bol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bolActionPerformed(evt);
            }
        });

        btn_iki.setBackground(new java.awt.Color(123, 123, 123));
        btn_iki.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_iki.setForeground(new java.awt.Color(255, 255, 255));
        btn_iki.setText("2");
        btn_iki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ikiActionPerformed(evt);
            }
        });

        btn_bir.setBackground(new java.awt.Color(123, 123, 123));
        btn_bir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_bir.setForeground(new java.awt.Color(255, 255, 255));
        btn_bir.setText("1");
        btn_bir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_birActionPerformed(evt);
            }
        });

        btn_alti.setBackground(new java.awt.Color(123, 123, 123));
        btn_alti.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_alti.setForeground(new java.awt.Color(255, 255, 255));
        btn_alti.setText("6");
        btn_alti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altiActionPerformed(evt);
            }
        });

        btn_bes.setBackground(new java.awt.Color(123, 123, 123));
        btn_bes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_bes.setForeground(new java.awt.Color(255, 255, 255));
        btn_bes.setText("5");
        btn_bes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_besActionPerformed(evt);
            }
        });

        btn_dort.setBackground(new java.awt.Color(123, 123, 123));
        btn_dort.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_dort.setForeground(new java.awt.Color(255, 255, 255));
        btn_dort.setText("4");
        btn_dort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dortActionPerformed(evt);
            }
        });

        btn_dokuz.setBackground(new java.awt.Color(123, 123, 123));
        btn_dokuz.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_dokuz.setForeground(new java.awt.Color(255, 255, 255));
        btn_dokuz.setText("9");
        btn_dokuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dokuzActionPerformed(evt);
            }
        });

        btn_kok.setBackground(new java.awt.Color(97, 97, 97));
        btn_kok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_kok.setForeground(new java.awt.Color(255, 255, 255));
        btn_kok.setText("√ ");
        btn_kok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kokActionPerformed(evt);
            }
        });

        btn_arti_eksi.setBackground(new java.awt.Color(97, 97, 97));
        btn_arti_eksi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_arti_eksi.setForeground(new java.awt.Color(255, 255, 255));
        btn_arti_eksi.setText("+/-");
        btn_arti_eksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arti_eksiActionPerformed(evt);
            }
        });

        btn_sil.setBackground(new java.awt.Color(97, 97, 97));
        btn_sil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sil.setForeground(new java.awt.Color(255, 255, 255));
        btn_sil.setText("C");
        btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silActionPerformed(evt);
            }
        });

        btn_yedi.setBackground(new java.awt.Color(123, 123, 123));
        btn_yedi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_yedi.setForeground(new java.awt.Color(255, 255, 255));
        btn_yedi.setText("7");
        btn_yedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yediActionPerformed(evt);
            }
        });

        btn_sekiz.setBackground(new java.awt.Color(123, 123, 123));
        btn_sekiz.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sekiz.setForeground(new java.awt.Color(255, 255, 255));
        btn_sekiz.setText("8");
        btn_sekiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sekizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_ekran)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_arti_eksi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kok, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_sifir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_virgul, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_esittir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_topla, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cikart, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_carp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txt_ekran, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bol, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kok, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_arti_eksi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_carp, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cikart, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_topla, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sifir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_virgul, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_esittir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void write(String text) {
        //txt_ekran.setText(txt_ekran.getText() + text);
        String Nums = txt_ekran.getText() + text;
        txt_ekran.setText(Nums);
    }
    private void txt_ekranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ekranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ekranActionPerformed

    private void btn_sifirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sifirActionPerformed
        write("0");
    }//GEN-LAST:event_btn_sifirActionPerformed

    private void btn_virgulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_virgulActionPerformed
        write(",");
    }//GEN-LAST:event_btn_virgulActionPerformed

    private void btn_toplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_toplaActionPerformed
        ps = 1;
        input1 = Double.parseDouble(txt_ekran.getText());
        txt_ekran.setText("");
    }//GEN-LAST:event_btn_toplaActionPerformed

    private void btn_ucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ucActionPerformed
        write("3");
    }//GEN-LAST:event_btn_ucActionPerformed

    private void btn_esittirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_esittirActionPerformed
        input2 = Double.parseDouble(txt_ekran.getText());
        switch (ps) {
            case 1:
                result = input1 + input2;
                break;
            case 2:
                result = input1 - input2;
                break;
            case 3:
                result = input1 * input2;
                break;
            case 4:
                result = input1 / input2;
                break;
        }
        txt_ekran.setText(String.valueOf(result));

    }//GEN-LAST:event_btn_esittirActionPerformed
            
    private void btn_cikartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikartActionPerformed
        ps = 2;
        input1 = Double.parseDouble(txt_ekran.getText());
        txt_ekran.setText("");
    }//GEN-LAST:event_btn_cikartActionPerformed

    private void btn_carpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carpActionPerformed
        ps = 3;
        input1 = Double.parseDouble(txt_ekran.getText());
        txt_ekran.setText("");
    }//GEN-LAST:event_btn_carpActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void btn_bolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bolActionPerformed
        ps = 4;
      input1 = Double.parseDouble(txt_ekran.getText());
          txt_ekran.setText("");
    }//GEN-LAST:event_btn_bolActionPerformed

    private void btn_ikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ikiActionPerformed
        write("2");
    }//GEN-LAST:event_btn_ikiActionPerformed

    private void btn_birActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_birActionPerformed
        write("1");
    }//GEN-LAST:event_btn_birActionPerformed

    private void btn_altiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altiActionPerformed
        write("6");
    }//GEN-LAST:event_btn_altiActionPerformed

    private void btn_besActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_besActionPerformed
        write("5");
    }//GEN-LAST:event_btn_besActionPerformed

    private void btn_dortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dortActionPerformed
        write("4");
    }//GEN-LAST:event_btn_dortActionPerformed

    private void btn_dokuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dokuzActionPerformed
        write("9");
    }//GEN-LAST:event_btn_dokuzActionPerformed

    private void btn_kokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kokActionPerformed
         try {
        double input1 = Double.parseDouble(txt_ekran.getText());

        
        double result = Math.sqrt(input1);

        // Sonucu ifadeye ekle
        txt_ekran.setText(String.valueOf(result));
    } catch (NumberFormatException e) {
        txt_ekran.setText("Hata");
    }
    }//GEN-LAST:event_btn_kokActionPerformed

    private void btn_arti_eksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arti_eksiActionPerformed
        double nums = Double.parseDouble(String.valueOf(txt_ekran.getText()));
        nums = nums * (-1);
        txt_ekran.setText(String.valueOf(nums));
    }//GEN-LAST:event_btn_arti_eksiActionPerformed

    private void btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silActionPerformed
        txt_ekran.setText("");
        result = 0;
        input1 = 0;
        input2 = 0;
        ps = 0;
    }//GEN-LAST:event_btn_silActionPerformed

    private void btn_yediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yediActionPerformed
        write("7");
    }//GEN-LAST:event_btn_yediActionPerformed

    private void btn_sekizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sekizActionPerformed
        write("8");
    }//GEN-LAST:event_btn_sekizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesapMakinesi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HesapMakinesi().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alti;
    private javax.swing.JButton btn_arti_eksi;
    private javax.swing.JButton btn_bes;
    private javax.swing.JButton btn_bir;
    private javax.swing.JButton btn_bol;
    private javax.swing.JButton btn_carp;
    private javax.swing.JButton btn_cikart;
    private javax.swing.JButton btn_dokuz;
    private javax.swing.JButton btn_dort;
    private javax.swing.JButton btn_esittir;
    private javax.swing.JButton btn_iki;
    private javax.swing.JButton btn_kok;
    private javax.swing.JButton btn_sekiz;
    private javax.swing.JButton btn_sifir;
    private javax.swing.JButton btn_sil;
    private javax.swing.JButton btn_topla;
    private javax.swing.JButton btn_uc;
    private javax.swing.JButton btn_virgul;
    private javax.swing.JButton btn_yedi;
    private javax.swing.JButton jButton25;
    private javax.swing.JTextField txt_ekran;
    // End of variables declaration//GEN-END:variables
}
